DEV-86 - translate coffeescript to typescript
algorithmiaio/algorithmia-nodejs pull request #17
Opened 2020-12-17 21:55 UTC by DaleHerring

2020-12-17 23:00 UTC, bnlb requested changes
Blockers are:

- Readme + examples
- Using `lib` instead of `build`.
- Updating tests to use a new account

2020-12-18 16:39 UTC, DaleHerring commented on src/HttpClient.ts
> +        this.httpClient = new hC.HttpClient('');
The useragent info is supposed to go there, I just forgot to add it back in, fix inc.

2021-01-05 17:41 UTC, bnlb commented on src/index.ts
> +export { Algorithmia } from '../src/Algorithmia';
```suggestion
export { Algorithmia as default } from './Algorithmia';
```

2021-01-05 17:41 UTC, bnlb commented on src/index.ts
> +export { DataFile, DataDir, DataList } from '../src/Data';
```suggestion
export { DataFile, DataDir, DataList } from './Data';
```

2021-01-05 17:45 UTC, bnlb commented on src/HttpClient.ts
> +    });
Let's update these functions to `await` responses instead of using promise chains. It's more intuitive for most people and more in line with current best practices.

```
async get(path: string) {
  const response = await this.httpClient.get(path, this.headers);

  return response.readBody();
}
```

2021-01-05 18:01 UTC, bnlb commented on src/Data.ts
> +}
The current Node client has [a lot more methods](https://github.com/algorithmiaio/algorithmia-nodejs/blob/master/lib/data.js#L33-L116) than are listed here. In order to keep our public API the same, they'll need to be added and match the same function signatures.

```
put(content, callback)

get(callback)

putString(content, callback)

putJson(content, callback)

getString(callback)

getJson(callback)

exists(callback)

delete(callback)
```

I like what you've done here returning promises directly, as that's more in line with what I'd expect as a JS dev, but I don't want to introduce an API change as a part of this PR. Our API should remain callback based for now. We can update to promises in a separate PR.

2021-01-05 18:06 UTC, bnlb commented on src/Data.ts
> +  }
We'll need all of the [current methods](https://github.com/algorithmiaio/algorithmia-nodejs/blob/master/lib/data.js#L118-L205) on the Directory instance as well:

```
create(callback)

file(filename)

putFile(filePath, callback)

iterator()

forEach(callback)

forEachFile(callback) 

forEachDir(callback)

exists(callback)

delete(force, callback)
```

2021-01-05 18:09 UTC, bnlb commented on src/AlgorithmExecutable.ts
> +    contentType = contentTypeHelper.contentTypeHelper(input);
The benefit of changing the contentType helper to a function instead of a class is that it simplifies the cases where it's used:

```
const contentType = getContentType(input);
```

2021-01-05 18:20 UTC, bnlb commented on src/AlgorithmExecutable.ts
> +      );
This is hard to follow. Can simplify a bit:

```
const pathname = version
  ? `${this.path}/${version}/`
  : `${this.path}/`;

const params = new URLSearchParams({
  output,
  stdout,
  timeout,
});

const fullPath = `${pathname}?${params.toString()}`;

return this.client.post(fullPath, input, contentType);
```

2021-01-05 18:24 UTC, bnlb commented on src/AlgorithmiaClient.ts
> +  dir(path: string): DataDir {
nit: The return types on these functions can be inferred, so you can drop them if you'd prefer and TypeScript will still know what's happening: `dir(path: string) {`

2021-01-05 18:28 UTC, bnlb commented on README.md
> +Create directories by instantiating a `DataDir` object and calling `post()`:
Let's change this method name back to `create`. Even though a POST is what's happening under the hood, from a user's perspective it's more intuitive to create a directory.

2021-01-05 18:45 UTC, bnlb commented on package.json
> +    "npm": "^6.14.9",
Are we using `npm` anywhere in the repo? I've never seen it installed in any project I've worked on. Should be safe to remove.

2021-01-05 18:46 UTC, bnlb commented on package.json
> +    "install": "^0.13.0",
What's this? Should be safe to remove.

2021-01-05 18:48 UTC, bnlb commented on README.md
> +client.algo('util/whoopsWrongAlgo').pipe('Hello, world!').then(x => { console.log(x) });
In all of the cases where we're demonstrating a response to a user, let's await instead.

```
const response = await client.algo('util/whoopsWrongAlgo').pipe('Hello, world!');
```

2021-01-05 18:50 UTC, bnlb commented on test/Data.test.ts
> +      ).file('data://dherring/DalesNotSoFunTime2/NahDawg.txt');
I'd still like this to be a dummy account that exists solely for the purpose of testing. Some username like `algorithmia-nodejs-e2e` or something obvious, then the API key used can come from that account.

2021-01-05 18:53 UTC, bnlb commented on test/Data.test.ts
> +  describe('algorithm file head call', () => {
Let's rename these test cases to reflect the method being tested, not the underlying HTTP method used.

```
describe('file.exists()', () => {
  it('should return true if a file exists', () => {
    // ...
  });
});

2021-01-05 18:54 UTC, bnlb commented on test/Data.test.ts
> +      expect(await dir.exists()).toBe(true);
This test is failing for me.

2021-01-05 18:55 UTC, bnlb commented on test/Data.test.ts
> +  describe('algorithm file put call', () => {
Just adding a note that once all the missing API methods that currently exist are added, tests should be created for those.

2021-01-05 19:01 UTC, bnlb requested changes
Main blockers:

- ~src/index.ts should have a default export of `Algorithmia`~
- The `examples/` folder should be added again (and updated if necessary to reflect API changes)
- ~Verify that the readme examples are all accurate after update~
- Add a CHANGELOG describing breaking changes (dropping support for callbacks in favor of promises, updating node version)
- Add missing methods that currently exist (`putFile`)
- ~Update tests with test cases once missing methods are added (`putFile`)
- ~Use a dummy `algorithmia-nodejs-e2e` user for tests instead of a personal account.~

2021-01-07 00:52 UTC, bnlb commented on test/Data.test.ts
> +      expect(await file.getBinary()).toBe('nah dawg');
Since the function is `getBinary`, I'd expect something [like this](https://github.com/algorithmiaio/algorithmia-nodejs/blob/master/examples/img-read.js).

2021-01-07 18:31 UTC, bnlb commented
@DaleHerring I've updated the blockers comment to reflect what's left.

2021-01-08 22:05 UTC, bnlb approved these changes

2021-01-08 22:20 UTC, merged