DEV-170 organization api calls
algorithmiaio/algorithmia-nodejs pull request #21
Opened 2021-01-16 02:46 UTC by DaleHerring

2021-01-18 16:15 UTC, jakemuntarsi submitted a review, later dismissed
Looks good to me

2021-01-19 17:59 UTC, bnlb commented on src/Algorithm.ts
> +  }
Let's move `createTestOrganization` and `editTestOrganization` to the test file itself. They can just be simple functions that return these objects.

2021-01-19 18:11 UTC, bnlb commented on src/AlgorithmiaClient.ts
> +        marker
Here's a good use case for template strings and URLSearchParams:
```
const path = `${this.algorithmsPrefix}/${username}/${algoName}/versions`;
const params = new URLSearchParams({ callable, limit, published });

if (marker) {
  params.set('marker', marker);
}

const search = `?${params.toString()}`;

return this.httpClient.get(`${this.apiAddress}${path}${search}`);

2021-01-19 18:11 UTC, bnlb commented on src/AlgorithmiaClient.ts
> +        marker
Same comment here about template strings + URLSearchParams

2021-01-19 18:13 UTC, bnlb commented on src/AlgorithmiaClient.ts
> +      '/logs'
Same comment about template strings

2021-01-19 18:18 UTC, bnlb commented on src/Algorithm.ts
> +class Organization {
Since this class is only being used in the test file, it'd be simpler to define this as an interface. Required/optional fields are [here](https://github.com/algorithmiaio/algorithmia/blob/develop/conf/OpenApiSpec/v1.0/AlgorithmiaSwaggerSpec.yaml#L2494-L2531).

2021-01-20 18:01 UTC, bnlb requested changes
Will approve once the linting errors are cleaned up.

2021-01-20 19:11 UTC, bnlb commented on test/AlgorithmiaClient.test.ts
> +    return requestObject;
Minor nit: since we're only using these objects in one place, let's just inline both of them  where they're used.

```
  describe('organization edit call', () => {
    it('edits for organization', async () => {
      const response = await Algorithmia.getClient(
        process.env.ALGORITHMIA_ADMIN_API_KEY,
        process.env.ALGORITHMIA_TEST_ADDRESS
      ).editOrganization('MyOrg1606332498213', {
        org_contact_name: 'some owner',
        org_email: 'SomeEmail@Whatsittoyou.com',
        org_label: 'myLabel',
        type_id: '3d40e3b0-d82a-11ea-9a3c-0ee5e2d35097',
        resource_type: 'organization',
        id: '3d9a9f41-d82a-11ea-9a3c-0ee5e2d35097',
      });

      expect(response).toBe('');
    });
  });

  describe('organization create call', () => {
    it('creates for organization', async () => {
      const testOrganization = {
        org_contact_name: 'some owner',
        org_email: 'SomeEmail@Whatsittoyou.com',
        org_label: 'myLabel',
        org_name: 'MyOrg' + Date.now(),
      };

      const organization: Organization = JSON.parse(
        await Algorithmia.getClient(
          process.env.ALGORITHMIA_ADMIN_API_KEY,
          process.env.ALGORITHMIA_TEST_ADDRESS
        ).createOrganization(testOrganization)
      );
      expect(organization.org_name).toBe(testOrganization.org_name);
    });
  });
```

2021-01-20 20:30 UTC, bnlb approved these changes

2021-01-20 20:40 UTC, merged