DEV-188 - create/edit organization fixes to support type id
algorithmiaio/algorithmia-nodejs pull request #22
Opened 2021-02-03 00:49 UTC by DaleHerring

2021-02-03 18:08 UTC, kennydaniel commented on src/AlgorithmiaClient.ts
> +      JSON.stringify(await this.organizationTypeIdChanger(requestObject))
does this need content type like the createOrganization code?

2021-02-03 18:16 UTC, DaleHerring commented on src/AlgorithmiaClient.ts
> +      JSON.stringify(await this.organizationTypeIdChanger(requestObject))
The put in the httpclient handles it

2021-02-03 18:23 UTC, jakemuntarsi approved these changes
looks good to me

2021-02-03 19:22 UTC, bnlb commented on src/AlgorithmiaClient.ts
> +      this.apiAddress + this.organizationsPrefix,
```suggestion
      `${this.apiAddress}${this.organizationsPrefix}`,
```

2021-02-03 19:33 UTC, bnlb commented on src/Algorithm.ts
> +}
```
interface OrgTypes {
  id: string;
  name: string;
}
```

2021-02-03 19:38 UTC, bnlb commented on src/AlgorithmiaClient.ts
> +        editedOrganization.type_id = type.id;
`type_id` can refer to two different things based on when it's read: initially it refers to the name of a type, and then it gets updated to an id. This could cause bugs as someone would assume it always refers to an id.

We should keep `type_id` as `undefined` or `null` when we're not sure what the value is yet, and add a new field `type_name` that people can set to `legacy`, `basic`, etc that we can hook into here.

2021-02-03 19:41 UTC, bnlb commented on src/AlgorithmiaClient.ts
> +    let editedOrganization: Organization = JSON.parse(JSON.stringify(requestObject));
I'd recommend creating a `clone` helper to make it clearer to new JS devs what's happening here. That functionality may be useful in the future.

```
const clone = (object: Record<string, unknown>) => 
  JSON.parse(JSON.stringify(object));

const editedOrganization: Organization = clone(requestObject);
```

2021-02-03 19:41 UTC, bnlb commented on src/AlgorithmiaClient.ts
> +    let typesMapList: OrgTypes[] = JSON.parse(await this.getOrgTypes());
Can we move the JSON parsing to inside `getOrgTypes`? The function name makes me think it's returning an array of strings.

2021-02-03 19:42 UTC, bnlb commented on src/AlgorithmiaClient.ts
> +      throw new TypeError("No matching value found");
+1 for handling this 💯

2021-02-03 19:43 UTC, bnlb commented on src/AlgorithmiaClient.ts
> +      throw new TypeError("No matching value found");
On second thought it'd be helpful to update to `No matching organization type found, should be one of 'legacy', 'basic', 'pro'.`

2021-02-03 19:43 UTC, bnlb commented on src/AlgorithmiaClient.ts
> +    return this.httpClient.get(this.apiAddress + this.organizationPrefix + '/types');
```suggestion
    return this.httpClient.get(`${this.apiAddress}${this.organizationPrefix}/types`);
```

2021-02-03 19:44 UTC, bnlb commented on src/AlgorithmiaClient.ts
> +      this.apiAddress + this.organizationsPrefix + '/' + orgName,
```suggestion
      `${this.apiAddress}${this.organizationsPrefix}/${orgName}`,
```

2021-02-03 19:45 UTC, bnlb commented on src/AlgorithmiaClient.ts
> +      this.apiAddress + this.organizationsPrefix + '/' + orgName
```suggestion
      `${this.apiAddress}${this.organizationsPrefix}/${orgName}`
```

2021-02-03 19:50 UTC, bnlb commented on src/AlgorithmiaClient.ts
> +      JSON.stringify(await this.organizationTypeIdChanger(requestObject)),
Can we cache this response value on the client instance? If some creates five orgs we'll be fetching the org types 5 times, but the response will be the same each time.
```
// constructor
private orgTypes = [];

// this function
if (!this.orgTypes.length) {
  this.orgTypes = await this.fetchOrgTypes();
}

// update object with appropriate id
```

2021-02-03 19:51 UTC, bnlb commented on src/AlgorithmiaClient.ts
> +  private organizationsPrefix = '/v1/organizations';
These look easy to mix up accidentally. I'd consider updating to `singleOrganizationPrefix` and `multipleOrganizationsPrefix`

2021-02-03 20:05 UTC, DaleHerring commented on src/AlgorithmiaClient.ts
> +        editedOrganization.type_id = type.id;
That's not what was asked of me to solve
https://algorithmia.atlassian.net/browse/DEV-188

2021-02-03 20:07 UTC, DaleHerring commented on src/AlgorithmiaClient.ts
> +    let editedOrganization: Organization = JSON.parse(JSON.stringify(requestObject));
?

2021-02-03 20:20 UTC, DaleHerring commented on src/AlgorithmiaClient.ts
> +  private organizationsPrefix = '/v1/organizations';
This sounds confusing to me, the s doesn't indicate that it is for singe or multiple instances, they are used for different endpoints

2021-02-03 21:22 UTC, DaleHerring commented on src/AlgorithmiaClient.ts
> +      throw new TypeError("No matching value found");
Then it would have to be updated if there is ever another type added

2021-02-03 21:26 UTC, DaleHerring commented on src/AlgorithmiaClient.ts
> +    let typesMapList: OrgTypes[] = JSON.parse(await this.getOrgTypes());
So you'd rather then endpoint return the parsed json object instead of the return from the server?

2021-02-03 21:47 UTC, DaleHerring commented on src/HttpClient.ts
>      return response.readBody();
It's written this way because that's not the only header in contentType and I added the other post to get around the formatting issues I was having with the custom type Input

2021-02-03 22:26 UTC, DaleHerring commented on src/AlgorithmiaClient.ts
> +      JSON.stringify(await this.organizationTypeIdChanger(requestObject)),
Handled this in organizationTypeIdChanger

2021-02-04 00:54 UTC, bnlb commented on src/AlgorithmiaClient.ts
> +      throw new TypeError("No matching value found");
That's fine, it's still more helpful than an error message that doesn't give you any context about what the value is or what it's looking for.

2021-02-04 00:55 UTC, bnlb commented on src/AlgorithmiaClient.ts
> +    let editedOrganization: Organization = JSON.parse(JSON.stringify(requestObject));
What duplicate code issue?

2021-02-04 01:01 UTC, bnlb commented on src/AlgorithmiaClient.ts
> +  private organizationsPrefix = '/v1/organizations';
`organizationPrefix` and `organizationsPrefix` are too similar and too easy to mix up. We're only using `v1/organization` for type info, so let's use `organizationTypePrefix` and `organizationsPrefix`.

2021-02-04 04:34 UTC, DaleHerring commented on src/AlgorithmiaClient.ts
> +    let editedOrganization: Organization = JSON.parse(JSON.stringify(requestObject));
I mean it wouldn't solve duplicate code

2021-02-18 17:24 UTC, warmbowski commented on src/AlgorithmiaClient.ts
> +        editedOrganization.type_id = type.id;
I agree with @bnlb here, having a property alternate between an enum and a string id isn't ideal. I'd rather those were separate properties too.

2021-02-18 17:45 UTC, DaleHerring commented on src/AlgorithmiaClient.ts
> +        editedOrganization.type_id = type.id;
That would require back-end changes. The value comes in as a named type. This is the same fix that went in to each library. The ticket is linked.

2021-02-18 18:39 UTC, bnlb commented on src/Algorithm.ts
> +}
This hasn't been resolved. The code style we use for interfaces uses semicolons on each line.

2021-02-18 18:43 UTC, bnlb commented on .github/CODEOWNERS
> +*   @algorithmiaio/developer-technologies-contractors
It's important that a consistent style is used for JS codebases across the company. The UX team owns these repos and signoff is required from members of UX. Contractors shouldn't be able to self-approve PRs without understanding the best practices, coding style, and concerns of the larger organization.
```suggestion

```

2021-02-18 18:45 UTC, DaleHerring commented on .github/CODEOWNERS
> +*   @algorithmiaio/developer-technologies-contractors
So my team shouldn't be able to review prs?

2021-02-18 18:49 UTC, DaleHerring commented on .github/CODEOWNERS
> +*   @algorithmiaio/developer-technologies-contractors
We were given ownership over the other libraries in which we work when we were hired. This and a few other new ones are the only ones that are different so far. The reason I added that line is so they would be automatically added to the pr, I suppose I can just do that manually from now on but I think it's important for the team to at least be notified.

2021-02-18 19:15 UTC, bnlb commented on src/AlgorithmiaClient.ts
> +        editedOrganization.type_id = type.id;
The ticket asks to add support for a `type_id` field for organizations, but it doesn't explicitly say that you have to use that key for both UUIDs and the user friendly names (and even if it did, the ticket would have to be updated).

When making requests to the API, `type_id` is a UUID. The values `legacy`, `pro`, `basic` have no meaning to the backend. It's confusing and error prone to use this key to mean both things.

This code is currently broken due to this. When making a request to `createOrganization`, the `type_id` field is successfully mapped to the underlying UUID, but the `editOrganization` uses a PUT call, which means the argument we're using is an object that we previously got from a GET call. That object isn't going to have a `type_id` field with a name of `legacy`, `basic`, or `pro`, since the backend will have sent the `type_id` back as a UUID during the GET call.

What this means is that when [this code](https://github.com/algorithmiaio/algorithmia-nodejs/blob/3a7eb877b6619751c58200e63912914917f70fe8/src/AlgorithmiaClient.ts#L243-L257) runs, an error will be thrown due to the fact that it won't find a type_id with one of the user friendly names. This isn't caught in the test because the editOrganization test uses the friendly name instead of what would actually happen if someone were making a request with an object they got from the backend.
 
`createOrganization` should be updated to match the following signature:

```
enum OrgType {
  Basic = 'basic',
  Legacy = 'legacy',
  Pro = 'pro'
}

createOrganization(org: OrgInput, type: OrgType): Promise<Organization>
```
The mapping of user friendly name to UUID only needs to happen when we're creating the organization, so the mapping can be ignored entirely for the edit call.

Once this change has been made, it should also be described in the changelog and a major version bump should occur.

2021-02-18 19:16 UTC, bnlb commented on test/AlgorithmiaClient.test.ts
> +        type_id: 'legacy',
This doesn't reflect the object we'd get back from a previous GET call. This should be a UUID to confirm the edit functionality works.

2021-02-18 19:20 UTC, bnlb commented on src/AlgorithmiaClient.ts
> +    let editedOrganization: Organization = JSON.parse(JSON.stringify(requestObject));
It's not about code duplication, it's about readability. `clone(object)` is much more readable than `JSON.parse(JSON.stringify(object))`.

2021-02-18 19:25 UTC, bnlb commented on src/AlgorithmiaClient.ts
> +      throw new TypeError("No matching organization type found, should be one of 'legacy', 'basic', 'pro'");
`TypeError` in JavaScript is used in cases where something can't happen because a JavaScript value is of the unexpected type (e.g., string vs null). In this instance the expected value and the actual value are both still objects, so a TypeError in that context is slightly misleading. I like your thinking on this, but it may confuse JS devs.

```suggestion
      throw new Error("No matching organization type found, should be one of 'legacy', 'basic', 'pro'");
```

2021-02-18 19:27 UTC, bnlb requested changes
Blockers:

- Codeowners file should only contain UX
- `editOrganization` test should use an object using a UUID instead of one of the user friendly strings
- `type_id` should only ever refer to a UUID. `createOrganization` signature should update to reflect this
- Changelog is updated and a major version bump happens

2021-02-18 19:42 UTC, bnlb commented on .github/CODEOWNERS
> +*   @algorithmiaio/developer-technologies-contractors
Completely agree that the team should be notified but the team should not be able to self approve PRs.

2021-02-24 23:22 UTC, bnlb commented on test/AlgorithmiaClient.test.ts
> +        ).getOrganization('MyOrg1614039696593'));
Let's update `getOrganization` so that it returns an `Organization` instead of a `string`, that will allow us to avoid calling JSON.parse() every time we use it.

2021-02-24 23:23 UTC, bnlb commented
Blockers:

- Failing CI
- `getOrganization` should return an `Organization` instead of a `string`

2021-02-26 00:34 UTC, bnlb approved these changes

2021-02-26 00:45 UTC, merged